/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IPT_Final2;
import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Settings.class.getResource("/Images/Server-Icon.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        EConnectionButton = new javax.swing.JButton();
        AboutUsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        LogoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SettingPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        Img = new javax.swing.JLabel();
        Button = new javax.swing.JButton();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        BottomPanel = new javax.swing.JPanel();
        AppVer = new javax.swing.JLabel();
        AppUp = new javax.swing.JLabel();
        AppList = new javax.swing.JLabel();
        AppRepair = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        Button2 = new javax.swing.JButton();
        Text6 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        Button3 = new javax.swing.JButton();
        Text8 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        Button4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(136, 113, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(1188, 678));

        Sidepanel.setBackground(new java.awt.Color(136, 113, 249));

        HomeButton.setBackground(new java.awt.Color(127, 57, 233));
        HomeButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-home-64.png"))); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeButton.setIconTextGap(60);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        EConnectionButton.setBackground(new java.awt.Color(127, 57, 233));
        EConnectionButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        EConnectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-connect-48.png"))); // NOI18N
        EConnectionButton.setText("Establish Connection");
        EConnectionButton.setBorder(null);
        EConnectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EConnectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EConnectionButton.setIconTextGap(24);
        EConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EConnectionButtonActionPerformed(evt);
            }
        });

        AboutUsButton.setBackground(new java.awt.Color(127, 57, 233));
        AboutUsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        AboutUsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-about-64.png"))); // NOI18N
        AboutUsButton.setText("About Us");
        AboutUsButton.setBorder(null);
        AboutUsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AboutUsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AboutUsButton.setIconTextGap(54);
        AboutUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(127, 57, 233));
        ExitButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-close-48.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setBorder(null);
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ExitButton.setIconTextGap(73);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Duck5.png"))); // NOI18N

        javax.swing.GroupLayout SidepanelLayout = new javax.swing.GroupLayout(Sidepanel);
        Sidepanel.setLayout(SidepanelLayout);
        SidepanelLayout.setHorizontalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AboutUsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addComponent(EConnectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidepanelLayout.setVerticalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EConnectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SettingPanel.setBackground(new java.awt.Color(136, 113, 249));

        TopPanel.setBackground(new java.awt.Color(136, 113, 249));
        TopPanel.setLayout(null);

        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TopHands.png"))); // NOI18N
        Img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TopPanel.add(Img);
        Img.setBounds(10, 0, 900, 160);

        Button.setBackground(new java.awt.Color(127, 57, 233));
        Button.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        Button.setText("Here");
        TopPanel.add(Button);
        Button.setBounds(420, 70, 114, 35);

        Text1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text1.setText("If you're looking for a guide");
        TopPanel.add(Text1);
        Text1.setBounds(369, 10, 200, 40);

        Text2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text2.setText("Then click this button");
        TopPanel.add(Text2);
        Text2.setBounds(390, 38, 160, 30);

        BottomPanel.setBackground(new java.awt.Color(136, 113, 249));
        BottomPanel.setLayout(null);

        AppVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Appver.png"))); // NOI18N
        AppVer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BottomPanel.add(AppVer);
        AppVer.setBounds(2, 10, 460, 230);

        AppUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AppUp.png"))); // NOI18N
        AppUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BottomPanel.add(AppUp);
        AppUp.setBounds(460, 10, 450, 230);

        AppList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AppList.png"))); // NOI18N
        AppList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BottomPanel.add(AppList);
        AppList.setBounds(460, 245, 450, 250);

        AppRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AppRepair.png"))); // NOI18N
        AppRepair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BottomPanel.add(AppRepair);
        AppRepair.setBounds(0, 245, 460, 250);

        Text3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text3.setText("Application Version");
        BottomPanel.add(Text3);
        Text3.setBounds(270, 75, 160, 40);

        Text4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Text4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text4.setText("Client Server Version 9.12.23");
        BottomPanel.add(Text4);
        Text4.setBounds(250, 100, 200, 40);

        Text5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Text5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text5.setText("Application is out of version!");
        BottomPanel.add(Text5);
        Text5.setBounds(700, 85, 190, 40);

        Button2.setBackground(new java.awt.Color(127, 57, 233));
        Button2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Button2.setText("Update");
        BottomPanel.add(Button2);
        Button2.setBounds(740, 120, 110, 40);

        Text6.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Text6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text6.setText("Having problems?");
        BottomPanel.add(Text6);
        Text6.setBounds(100, 320, 140, 40);

        Text7.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Text7.setText("Try clicking this button!");
        BottomPanel.add(Text7);
        Text7.setBounds(87, 355, 170, 20);
        Text7.getAccessibleContext().setAccessibleName("Try clicking this button");

        Button3.setBackground(new java.awt.Color(127, 57, 233));
        Button3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Button3.setText("Repair");
        BottomPanel.add(Button3);
        Button3.setBounds(110, 382, 120, 40);

        Text8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Text8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text8.setText("Still having problems?");
        BottomPanel.add(Text8);
        Text8.setBounds(527, 325, 150, 30);

        Text9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Text9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text9.setText("Try going back to our old versions");
        BottomPanel.add(Text9);
        Text9.setBounds(477, 355, 240, 19);

        Button4.setBackground(new java.awt.Color(127, 57, 233));
        Button4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Button4.setText("Redirect");
        BottomPanel.add(Button4);
        Button4.setBounds(543, 382, 100, 40);

        javax.swing.GroupLayout SettingPanelLayout = new javax.swing.GroupLayout(SettingPanel);
        SettingPanel.setLayout(SettingPanelLayout);
        SettingPanelLayout.setHorizontalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
                .addContainerGap())
        );
        SettingPanelLayout.setVerticalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingPanelLayout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(SettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        this.setVisible(false);
        new NetworkUI().setVisible(true);  
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void EConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EConnectionButtonActionPerformed
        this.setVisible(false);
        new EstablishConnection().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_EConnectionButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsButtonActionPerformed
    this.setVisible(false);
    new AboutUs().setVisible(true);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsButton;
    private javax.swing.JLabel AppList;
    private javax.swing.JLabel AppRepair;
    private javax.swing.JLabel AppUp;
    private javax.swing.JLabel AppVer;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton Button;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton EConnectionButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel Img;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
