/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IPT_Final2;

import java.net.Socket;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author User
 */
public class ManageNetwork extends javax.swing.JFrame {
    private String[] ipArray;
    private int currentIndex = 0;
    /**
     * Creates new form ManageNetwork
     */
    EstablishConnection establishConnection = new EstablishConnection();
    private Socket socket;
    boolean isClicked = false;
    
    public ManageNetwork() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(ManageNetwork.class.getResource("/Images/Server-Icon.png")));
        initComponents();
        ipArray = new String[5];
        this.setResizable(false);
        HistoryLogsButton.setEnabled(false);
    }
    
    public void handleNewConnection(Socket socket) {
        if (socket != null) {
            String ipAddress = socket.getInetAddress().getHostAddress();
            String HostName = socket.getInetAddress().getHostName();
            // Store the IP address in the array
            ipArray[currentIndex] = ipAddress;

            // Update the UI with the IP address of the new client
            switch (currentIndex) {
                case 0:
                	ConUser1.setText(HostName);
                	IPAdd1TextField.setText(ipAddress);
                    break;
                case 1:
                	ConUser2.setText(HostName);
                	IPAdd2TextField.setText(ipAddress);
                    break;
                case 2:
                	ConUser3.setText(HostName);
                	IPAdd3TextField.setText(ipAddress);
                    break;
                case 3:
                	ConUser4.setText(HostName);
                	IPAdd4TextField.setText(ipAddress);
                    break;
                case 4:
                	ConUser5.setText(HostName);
                	IPAdd5TextField.setText(ipAddress);
                    break;
                    
                case 5:
                	ConUser6.setText(HostName);
                	IPAdd6TextField.setText(ipAddress);
                    break;
            }
            // Update the current index for the next IP address
            currentIndex = (currentIndex + 1) % ipArray.length;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        ManageButton = new javax.swing.JButton();
        HistoryLogsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NetworkBox = new javax.swing.JPanel();
        ConPanel1 = new javax.swing.JPanel();
        ConUser1 = new javax.swing.JLabel();
        IPAdd1TextField = new javax.swing.JLabel();
        Con1Button = new javax.swing.JButton();
        ConPanel3 = new javax.swing.JPanel();
        ConUser3 = new javax.swing.JLabel();
        IPAdd3TextField = new javax.swing.JLabel();
        Con3Button = new javax.swing.JButton();
        Con3Button.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		establishConnection.disconnectServer_fromManageNetwork();
                ConUser3.setText("Client Disconnected");
                IPAdd3TextField.setText("");
        	}
        });
        ConPanel4 = new javax.swing.JPanel();
        ConUser4 = new javax.swing.JLabel();
        IPAdd4TextField = new javax.swing.JLabel();
        Con4Button = new javax.swing.JButton();
        Con4Button.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		establishConnection.disconnectServer_fromManageNetwork();
                ConUser4.setText("Client Disconnected");
                IPAdd4TextField.setText("");
        	}
        });
        ConPanel2 = new javax.swing.JPanel();
        ConUser2 = new javax.swing.JLabel();
        IPAdd2TextField = new javax.swing.JLabel();
        Con2Button = new javax.swing.JButton();
        Con2Button.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		establishConnection.disconnectServer_fromManageNetwork();
                ConUser2.setText("Client Disconnected");
                IPAdd2TextField.setText("");
        	}
        });
        ConPanel5 = new javax.swing.JPanel();
        ConUser5 = new javax.swing.JLabel();
        IPAdd5TextField = new javax.swing.JLabel();
        Con5Button = new javax.swing.JButton();
        Con5Button.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		establishConnection.disconnectServer_fromManageNetwork();
                ConUser5.setText("Client Disconnected");
                IPAdd5TextField.setText("");
        	}
        });
        ConPanel6 = new javax.swing.JPanel();
        ConUser6 = new javax.swing.JLabel();
        IPAdd6TextField = new javax.swing.JLabel();
        Con6Button = new javax.swing.JButton();
        Con6Button.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		establishConnection.disconnectServer_fromManageNetwork();
                ConUser6.setText("Client Disconnected");
                IPAdd6TextField.setText("");
        	}
        });
        Numbering = new javax.swing.JLabel();
        Connected1 = new javax.swing.JLabel();
        Connected2 = new javax.swing.JLabel();
        Connected3 = new javax.swing.JLabel();
        Connected4 = new javax.swing.JLabel();
        Connected5 = new javax.swing.JLabel();
        Connected6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Img1 = new javax.swing.JLabel();
        Img2 = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(136, 113, 249));
        Background.setPreferredSize(new java.awt.Dimension(1200, 676));

        Sidepanel.setBackground(new java.awt.Color(136, 113, 249));

        ManageButton.setBackground(new java.awt.Color(127, 57, 233));
        ManageButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ManageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-manage-64.png"))); // NOI18N
        ManageButton.setText("Manage Networks");
        ManageButton.setBorder(null);
        ManageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ManageButton.setIconTextGap(14);

        HistoryLogsButton.setBackground(new java.awt.Color(127, 57, 233));
        HistoryLogsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HistoryLogsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-activity-history-64.png"))); // NOI18N
        HistoryLogsButton.setText("History Logs");
        HistoryLogsButton.setBorder(null);
        HistoryLogsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HistoryLogsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HistoryLogsButton.setIconTextGap(30);
        HistoryLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryLogsButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(127, 57, 233));
        ExitButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-close-48.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setBorder(null);
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ExitButton.setIconTextGap(73);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Duck3.png"))); // NOI18N

        javax.swing.GroupLayout SidepanelLayout = new javax.swing.GroupLayout(Sidepanel);
        Sidepanel.setLayout(SidepanelLayout);
        SidepanelLayout.setHorizontalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistoryLogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidepanelLayout.setVerticalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(ManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        NetworkBox.setBackground(new java.awt.Color(127, 57, 233));
        NetworkBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        ConPanel1.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel1.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser1.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser1.setForeground(new java.awt.Color(0, 0, 0));
        ConUser1.setText("Client");

        IPAdd1TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd1TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con1Button.setBackground(new java.awt.Color(127, 57, 233));
        Con1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disconnect.png"))); // NOI18N
        Con1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        		establishConnection.disconnectServer_fromManageNetwork();
                ConUser1.setText("Client Disconnected");
                IPAdd1TextField.setText("");
        	}
        });

        javax.swing.GroupLayout ConPanel1Layout = new javax.swing.GroupLayout(ConPanel1);
        ConPanel1.setLayout(ConPanel1Layout);
        ConPanel1Layout.setHorizontalGroup(
            ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser1)
                .addGap(259, 259, 259)
                .addComponent(IPAdd1TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(Con1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel1Layout.setVerticalGroup(
            ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd1TextField)
                            .addComponent(ConUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel3.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel3.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser3.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser3.setForeground(new java.awt.Color(0, 0, 0));
        ConUser3.setText("Client");

        IPAdd3TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd3TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con3Button.setBackground(new java.awt.Color(127, 57, 233));
        Con3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disconnect.png"))); // NOI18N

        javax.swing.GroupLayout ConPanel3Layout = new javax.swing.GroupLayout(ConPanel3);
        ConPanel3.setLayout(ConPanel3Layout);
        ConPanel3Layout.setHorizontalGroup(
            ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser3)
                .addGap(259, 259, 259)
                .addComponent(IPAdd3TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(Con3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel3Layout.setVerticalGroup(
            ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd3TextField)
                            .addComponent(ConUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel4.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel4.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser4.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser4.setForeground(new java.awt.Color(0, 0, 0));
        ConUser4.setText("Client");

        IPAdd4TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd4TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con4Button.setBackground(new java.awt.Color(127, 57, 233));
        Con4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disconnect.png"))); // NOI18N

        javax.swing.GroupLayout ConPanel4Layout = new javax.swing.GroupLayout(ConPanel4);
        ConPanel4.setLayout(ConPanel4Layout);
        ConPanel4Layout.setHorizontalGroup(
            ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser4)
                .addGap(259, 259, 259)
                .addComponent(IPAdd4TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(Con4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel4Layout.setVerticalGroup(
            ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd4TextField)
                            .addComponent(ConUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel2.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel2.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser2.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser2.setForeground(new java.awt.Color(0, 0, 0));
        ConUser2.setText("Client");

        IPAdd2TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd2TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con2Button.setBackground(new java.awt.Color(127, 57, 233));
        Con2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disconnect.png"))); // NOI18N

        javax.swing.GroupLayout ConPanel2Layout = new javax.swing.GroupLayout(ConPanel2);
        ConPanel2.setLayout(ConPanel2Layout);
        ConPanel2Layout.setHorizontalGroup(
            ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser2)
                .addGap(259, 259, 259)
                .addComponent(IPAdd2TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(Con2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel2Layout.setVerticalGroup(
            ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd2TextField)
                            .addComponent(ConUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel5.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel5.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser5.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser5.setForeground(new java.awt.Color(0, 0, 0));
        ConUser5.setText("Client");

        IPAdd5TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd5TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con5Button.setBackground(new java.awt.Color(127, 57, 233));
        Con5Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disconnect.png"))); // NOI18N

        javax.swing.GroupLayout ConPanel5Layout = new javax.swing.GroupLayout(ConPanel5);
        ConPanel5Layout.setHorizontalGroup(
        	ConPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(ConPanel5Layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(ConUser5)
        			.addGap(258)
        			.addComponent(IPAdd5TextField)
        			.addPreferredGap(ComponentPlacement.RELATED, 425, Short.MAX_VALUE)
        			.addComponent(Con5Button, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        			.addGap(24))
        );
        ConPanel5Layout.setVerticalGroup(
        	ConPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(ConPanel5Layout.createSequentialGroup()
        			.addGroup(ConPanel5Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(ConPanel5Layout.createSequentialGroup()
        					.addGap(12)
        					.addComponent(Con5Button, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE))
        				.addGroup(ConPanel5Layout.createSequentialGroup()
        					.addGap(21)
        					.addGroup(ConPanel5Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(ConUser5, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        						.addComponent(IPAdd5TextField))))
        			.addContainerGap(11, Short.MAX_VALUE))
        );
        ConPanel5.setLayout(ConPanel5Layout);

        ConPanel6.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel6.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser6.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser6.setForeground(new java.awt.Color(0, 0, 0));
        ConUser6.setText("Client");

        IPAdd6TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd6TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con6Button.setBackground(new java.awt.Color(127, 57, 233));
        Con6Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disconnect.png"))); // NOI18N

        javax.swing.GroupLayout ConPanel6Layout = new javax.swing.GroupLayout(ConPanel6);
        ConPanel6.setLayout(ConPanel6Layout);
        ConPanel6Layout.setHorizontalGroup(
            ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser6)
                .addGap(259, 259, 259)
                .addComponent(IPAdd6TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(Con6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel6Layout.setVerticalGroup(
            ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd6TextField)
                            .addComponent(ConUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Numbering.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Numbering.setForeground(new java.awt.Color(0, 0, 0));
        Numbering.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Numbering.setText("No.");

        Connected1.setBackground(new java.awt.Color(0, 0, 0));
        Connected1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected1.setForeground(new java.awt.Color(0, 0, 0));
        Connected1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected1.setText("1");

        Connected2.setBackground(new java.awt.Color(0, 0, 0));
        Connected2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected2.setForeground(new java.awt.Color(0, 0, 0));
        Connected2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected2.setText("2");

        Connected3.setBackground(new java.awt.Color(0, 0, 0));
        Connected3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected3.setForeground(new java.awt.Color(0, 0, 0));
        Connected3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected3.setText("3");

        Connected4.setBackground(new java.awt.Color(0, 0, 0));
        Connected4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected4.setForeground(new java.awt.Color(0, 0, 0));
        Connected4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected4.setText("4");

        Connected5.setBackground(new java.awt.Color(0, 0, 0));
        Connected5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected5.setForeground(new java.awt.Color(0, 0, 0));
        Connected5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected5.setText("5");

        Connected6.setBackground(new java.awt.Color(0, 0, 0));
        Connected6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected6.setForeground(new java.awt.Color(0, 0, 0));
        Connected6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected6.setText("6");

        javax.swing.GroupLayout NetworkBoxLayout = new javax.swing.GroupLayout(NetworkBox);
        NetworkBox.setLayout(NetworkBoxLayout);
        NetworkBoxLayout.setHorizontalGroup(
            NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(NetworkBoxLayout.createSequentialGroup()
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Numbering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Connected1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ConPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ConPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ConPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ConPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        NetworkBoxLayout.setVerticalGroup(
            NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetworkBoxLayout.createSequentialGroup()
                .addComponent(Numbering, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(136, 113, 249));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(null);

        Img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Catvibing (1).gif"))); // NOI18N
        jPanel2.add(Img1);
        Img1.setBounds(2, 0, 280, 150);

        Img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FinalCat.gif"))); // NOI18N
        jPanel2.add(Img2);
        Img2.setBounds(637, 0, 300, 154);

        Text1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text1.setText("Want to explore more stickers and images?");
        jPanel2.add(Text1);
        Text1.setBounds(300, 40, 340, 40);

        Text2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text2.setText("Come visit our site to learn more things!");
        jPanel2.add(Text2);
        Text2.setBounds(320, 70, 300, 21);

        Button1.setBackground(new java.awt.Color(127, 57, 233));
        Button1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Button1.setText("Redirect");
        jPanel2.add(Button1);
        Button1.setBounds(400, 100, 150, 30);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NetworkBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NetworkBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistoryLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryLogsButtonActionPerformed
        this.setVisible(false);
        new HistoryLogs().setVisible(true);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryLogsButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ManageNetwork(IP_Address,count).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Con1Button;
    private javax.swing.JButton Con2Button;
    private javax.swing.JButton Con3Button;
    private javax.swing.JButton Con4Button;
    private javax.swing.JButton Con5Button;
    private javax.swing.JButton Con6Button;
    private javax.swing.JPanel ConPanel1;
    private javax.swing.JPanel ConPanel2;
    private javax.swing.JPanel ConPanel3;
    private javax.swing.JPanel ConPanel4;
    private javax.swing.JPanel ConPanel5;
    private javax.swing.JPanel ConPanel6;
    private javax.swing.JLabel ConUser1;
    private javax.swing.JLabel ConUser2;
    private javax.swing.JLabel ConUser3;
    private javax.swing.JLabel ConUser4;
    private javax.swing.JLabel ConUser5;
    private javax.swing.JLabel ConUser6;
    private javax.swing.JLabel Connected1;
    private javax.swing.JLabel Connected2;
    private javax.swing.JLabel Connected3;
    private javax.swing.JLabel Connected4;
    private javax.swing.JLabel Connected5;
    private javax.swing.JLabel Connected6;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HistoryLogsButton;
    private javax.swing.JLabel IPAdd1TextField;
    private javax.swing.JLabel IPAdd2TextField;
    private javax.swing.JLabel IPAdd3TextField;
    private javax.swing.JLabel IPAdd4TextField;
    private javax.swing.JLabel IPAdd5TextField;
    private javax.swing.JLabel IPAdd6TextField;
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Img2;
    private javax.swing.JButton ManageButton;
    private javax.swing.JPanel NetworkBox;
    private javax.swing.JLabel Numbering;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
