/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IPT_Final2;

import com.sun.management.OperatingSystemMXBean;
import java.awt.event.*;
import java.lang.management.ManagementFactory;
import java.net.Socket;
import javax.swing.*;

/**
 *
 * @author User
 */
public class NetworkUI extends javax.swing.JFrame {

    /**
     * Creates new form NetworkUI
     */
    private Timer timer, timer_date;


    public NetworkUI() {
        initComponents();
        this.setResizable(false);
        CPUpercentage();
    }
     
    public void CPUpercentage() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                OperatingSystemMXBean osBean = ManagementFactory.getPlatformMXBean(OperatingSystemMXBean.class);
                    // What % load the overall system is at, from 0.0-1.0
                    double systemLoad = osBean.getSystemCpuLoad() * 100.0;
                        PercentNumTextField.setText("");
                        PercentNumTextField.setText(String.format("%.2f", systemLoad) + "%");
                    }
                });
                timer.setInitialDelay(0);
                timer.start();
            }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        EConnectionButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        AboutUsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        LogoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TopInfoPanel = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();
        TextPanel = new javax.swing.JLabel();
        TextPanel2 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FeedbackButton = new javax.swing.JButton();
        TextPanel3 = new javax.swing.JLabel();
        TextPanel4 = new javax.swing.JLabel();
        CPUPanel = new javax.swing.JPanel();
        CPUPerformance = new javax.swing.JLabel();
        ImageCircle = new javax.swing.JLabel();
        PercentNumTextField = new javax.swing.JLabel();
        ContactPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MidPanel = new javax.swing.JPanel();
        ImgPanel = new javax.swing.JLabel();
        Img1 = new javax.swing.JLabel();
        Img2 = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(136, 113, 249));

        Sidepanel.setBackground(new java.awt.Color(136, 113, 249));

        HomeButton.setBackground(new java.awt.Color(127, 57, 233));
        HomeButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-home-64.png"))); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeButton.setIconTextGap(60);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        EConnectionButton.setBackground(new java.awt.Color(127, 57, 233));
        EConnectionButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        EConnectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-connect-48.png"))); // NOI18N
        EConnectionButton.setText("Establish Connection");
        EConnectionButton.setBorder(null);
        EConnectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EConnectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EConnectionButton.setIconTextGap(24);
        EConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EConnectionButtonActionPerformed(evt);
            }
        });

        SettingsButton.setBackground(new java.awt.Color(127, 57, 233));
        SettingsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        SettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-settings-48.png"))); // NOI18N
        SettingsButton.setText("Settings");
        SettingsButton.setBorder(null);
        SettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SettingsButton.setIconTextGap(60);
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        AboutUsButton.setBackground(new java.awt.Color(127, 57, 233));
        AboutUsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        AboutUsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-about-64.png"))); // NOI18N
        AboutUsButton.setText("About Us");
        AboutUsButton.setBorder(null);
        AboutUsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AboutUsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AboutUsButton.setIconTextGap(54);
        AboutUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(127, 57, 233));
        ExitButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-close-48.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setBorder(null);
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ExitButton.setIconTextGap(73);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Duck2.png"))); // NOI18N

        javax.swing.GroupLayout SidepanelLayout = new javax.swing.GroupLayout(Sidepanel);
        Sidepanel.setLayout(SidepanelLayout);
        SidepanelLayout.setHorizontalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EConnectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AboutUsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidepanelLayout.setVerticalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EConnectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TopInfoPanel.setBackground(new java.awt.Color(136, 113, 249));
        TopInfoPanel.setLayout(null);

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Example3.png"))); // NOI18N
        Image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TopInfoPanel.add(Image);
        Image.setBounds(0, 0, 450, 205);

        TextPanel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TextPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextPanel.setText("Having problems with the old version?");
        TopInfoPanel.add(TextPanel);
        TextPanel.setBounds(160, 60, 260, 40);

        TextPanel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TextPanel2.setText("Get the lastest version now!");
        TopInfoPanel.add(TextPanel2);
        TextPanel2.setBounds(190, 83, 190, 40);

        UpdateButton.setBackground(new java.awt.Color(255, 191, 175));
        UpdateButton.setForeground(new java.awt.Color(0, 0, 0));
        UpdateButton.setText("Update");
        TopInfoPanel.add(UpdateButton);
        UpdateButton.setBounds(200, 120, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Example5.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TopInfoPanel.add(jLabel2);
        jLabel2.setBounds(460, 0, 462, 205);

        FeedbackButton.setBackground(new java.awt.Color(255, 191, 175));
        FeedbackButton.setForeground(new java.awt.Color(0, 0, 0));
        FeedbackButton.setText("Send Feedback");
        TopInfoPanel.add(FeedbackButton);
        FeedbackButton.setBounds(670, 120, 160, 30);

        TextPanel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TextPanel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextPanel3.setText("Enjoying our application?");
        TopInfoPanel.add(TextPanel3);
        TextPanel3.setBounds(630, 60, 256, 43);

        TextPanel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TextPanel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextPanel4.setText("Kindly send us a feedback!");
        TopInfoPanel.add(TextPanel4);
        TextPanel4.setBounds(660, 80, 197, 46);

        CPUPanel.setBackground(new java.awt.Color(199, 244, 90));

        CPUPerformance.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        CPUPerformance.setForeground(new java.awt.Color(0, 0, 0));
        CPUPerformance.setText("CPU Performance");

        ImageCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Percentage Circle.png"))); // NOI18N

        PercentNumTextField.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        PercentNumTextField.setForeground(new java.awt.Color(51, 51, 51));
        PercentNumTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CPUPanelLayout = new javax.swing.GroupLayout(CPUPanel);
        CPUPanel.setLayout(CPUPanelLayout);
        CPUPanelLayout.setHorizontalGroup(
            CPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPUPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(CPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPUPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(CPUPanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(PercentNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CPUPanelLayout.setVerticalGroup(
            CPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPUPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(CPUPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(CPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CPUPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(PercentNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ImageCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ContactPanel.setBackground(new java.awt.Color(199, 244, 90));
        ContactPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contact Us");
        ContactPanel.add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 40);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Full Name:");
        ContactPanel.add(jLabel3);
        jLabel3.setBounds(10, 50, 130, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email Address");
        ContactPanel.add(jLabel4);
        jLabel4.setBounds(10, 110, 130, 30);
        ContactPanel.add(jTextField2);
        jTextField2.setBounds(10, 200, 490, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ContactPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 490, 86);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Message:");
        ContactPanel.add(jLabel5);
        jLabel5.setBounds(10, 230, 80, 30);
        ContactPanel.add(jTextField3);
        jTextField3.setBounds(10, 80, 490, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        ContactPanel.add(jTextField4);
        jTextField4.setBounds(10, 140, 490, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Text Subject:");
        ContactPanel.add(jLabel6);
        jLabel6.setBounds(10, 180, 120, 21);

        jButton1.setBackground(new java.awt.Color(127, 57, 233));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        ContactPanel.add(jButton1);
        jButton1.setBounds(370, 10, 120, 40);

        MidPanel.setBackground(new java.awt.Color(136, 113, 249));
        MidPanel.setLayout(null);

        ImgPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        MidPanel.add(ImgPanel);
        ImgPanel.setBounds(0, 0, 923, 121);

        Img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pompom2.png"))); // NOI18N
        MidPanel.add(Img1);
        Img1.setBounds(710, 0, 210, 120);

        Img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pompom3.png"))); // NOI18N
        MidPanel.add(Img2);
        Img2.setBounds(0, 0, 230, 120);

        Text1.setFont(new java.awt.Font("Century Gothic", 3, 19)); // NOI18N
        Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text1.setText("Don't forget to exercise after a long day of work!");
        MidPanel.add(Text1);
        Text1.setBounds(235, 0, 470, 90);

        Text2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        Text2.setText("Pom Pom is concerned about you, so take a break and relax yourself");
        MidPanel.add(Text2);
        Text2.setBounds(235, 14, 470, 110);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(CPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                    .addComponent(MidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addComponent(TopInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPUPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(Sidepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void EConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EConnectionButtonActionPerformed
    this.setVisible(false);
    new EstablishConnection().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_EConnectionButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
    this.setVisible(false);
    new Settings().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void AboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsButtonActionPerformed
    this.setVisible(false);
    new AboutUs().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsButtonActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new NetworkUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsButton;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel CPUPanel;
    private javax.swing.JLabel CPUPerformance;
    private javax.swing.JPanel ContactPanel;
    private javax.swing.JButton EConnectionButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton FeedbackButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel ImageCircle;
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Img2;
    private javax.swing.JLabel ImgPanel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel MidPanel;
    private javax.swing.JLabel PercentNumTextField;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel TextPanel;
    private javax.swing.JLabel TextPanel2;
    private javax.swing.JLabel TextPanel3;
    private javax.swing.JLabel TextPanel4;
    private javax.swing.JPanel TopInfoPanel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
