/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IPT_Final;

import IPT_Final.NetworkUI;
import IPT_Final.HistoryLogs;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.*;
import javax.swing.SwingWorker;

/**
 *
 * @author User
 */
public class EstablishConnection extends javax.swing.JFrame {

    /**
     * Creates new form EstablishConnection
     */
//    private NetworkUI NetworkUI;
    boolean isClicked;
    private int serverport;
    private int count=0;
    private String IP_Address;
    Socket socket;
    
    
    public EstablishConnection(String IP_Address, int count, Socket socket) {
        initComponents();
        this.setResizable(false);
    }
    
    public void createServer(){
        try (ServerSocket listener = new ServerSocket(serverport)) {
        Con2TextField.setText("");
        Con2TextField.setText("The server is running...");
        
        }
        catch(Exception e) {
        Con2TextField.setText("");
        Con2TextField.setText("Error is found");
            e.printStackTrace();
    }}
        
    public void startServer() {
         
    if (isClicked==true) {
            try (ServerSocket listener = new ServerSocket(serverport)) {
                Con4TextField.setText("");
                Con4TextField.setText("Using server socket: " + serverport);

                    socket = listener.accept();
                    
                    InetAddress clientAddress = socket.getInetAddress(); //GET IP ADDRESS
                    IP_Address = clientAddress.getHostAddress();
                    //count++;
                    
                    Con3TextField.setText("");
                    Con3TextField.setText("IP Address & Host Name: " + clientAddress.getHostAddress() +
                        " ("+ clientAddress.getHostName() + ") ");
                    
                    Con1TextField.setText("");
                    Con1TextField.setText("Port No.: " + socket.getPort()); //GET PORT NO.

                    if(count<=5){
                        HistoryLogs HistoryLogs = new HistoryLogs(IP_Address,count,socket);
                        HistoryLogs.setVisible(true);
                    }
                    
                    
                    BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                    PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
//                    if (NetworkUI != null) {
//                        NetworkUI.upTime();
//                    } else {
//                        Con4TextField.setText("");
//                        Con4TextField.setText("UpTime Error");
//                    }
                                        
                    String inputLine;
                    while ((inputLine = in.readLine()) != null) {
                        System.out.println(inputLine);
                        out.println(inputLine);
                    }
                    } catch(Exception e) {
                    Con4TextField.setText("");
                    Con4TextField.setText("Error is found");
                            e.printStackTrace();
                            
                    }
                } else {
                    Con4TextField.setText("");
                    Con4TextField.setText("Create a server first and try again.");
    }}
   
    public void disconnectServer() {
         try {
             if (socket != null) {
                 socket.close();
                 Con4TextField.setText("");
                 Con4TextField.setText("Client disconnected.");
             }
         } catch (IOException e) {
             Con4TextField.setText("");
             Con4TextField.setText("Error while disconnecting client: " + e.getMessage());
         }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        EConnectionButton = new javax.swing.JButton();
        ManageButton = new javax.swing.JButton();
        HistoryLogsButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        AboutUsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        LogoLabel = new javax.swing.JLabel();
        TextResultPanel = new javax.swing.JPanel();
        StatusInfo = new javax.swing.JLabel();
        Con1TextField = new javax.swing.JLabel();
        Con2TextField = new javax.swing.JLabel();
        Con3TextField = new javax.swing.JLabel();
        Con4TextField = new javax.swing.JLabel();
        SearchPanelBG = new javax.swing.JPanel();
        SearchBarButton = new javax.swing.JButton();
        SearchBarTextField = new javax.swing.JTextField();
        TopInfo2Panel = new javax.swing.JPanel();
        StopServerButton = new javax.swing.JButton();
        StartServerButton = new javax.swing.JButton();
        Info1 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        Info4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(136, 113, 249));
        Background.setPreferredSize(new java.awt.Dimension(2404, 674));

        SidePanel.setBackground(new java.awt.Color(136, 113, 249));
        SidePanel.setPreferredSize(new java.awt.Dimension(247, 674));

        HomeButton.setBackground(new java.awt.Color(127, 57, 233));
        HomeButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeButton.setIconTextGap(60);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        EConnectionButton.setBackground(new java.awt.Color(127, 57, 233));
        EConnectionButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        EConnectionButton.setText("Establish Connection");
        EConnectionButton.setBorder(null);
        EConnectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EConnectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EConnectionButton.setIconTextGap(24);
        EConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EConnectionButtonActionPerformed(evt);
            }
        });

        ManageButton.setBackground(new java.awt.Color(127, 57, 233));
        ManageButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ManageButton.setText("Manage Networks");
        ManageButton.setBorder(null);
        ManageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ManageButton.setIconTextGap(14);
        ManageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageButtonActionPerformed(evt);
            }
        });

        HistoryLogsButton.setBackground(new java.awt.Color(127, 57, 233));
        HistoryLogsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HistoryLogsButton.setText("History Logs");
        HistoryLogsButton.setBorder(null);
        HistoryLogsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HistoryLogsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HistoryLogsButton.setIconTextGap(30);
        HistoryLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryLogsButtonActionPerformed(evt);
            }
        });

        SettingsButton.setBackground(new java.awt.Color(127, 57, 233));
        SettingsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        SettingsButton.setText("Settings");
        SettingsButton.setBorder(null);
        SettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SettingsButton.setIconTextGap(60);

        AboutUsButton.setBackground(new java.awt.Color(127, 57, 233));
        AboutUsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        AboutUsButton.setText("About Us");
        AboutUsButton.setBorder(null);
        AboutUsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AboutUsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AboutUsButton.setIconTextGap(54);

        ExitButton.setBackground(new java.awt.Color(127, 57, 233));
        ExitButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setBorder(null);
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ExitButton.setIconTextGap(73);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EConnectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
            .addComponent(ManageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistoryLogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AboutUsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EConnectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TextResultPanel.setBackground(new java.awt.Color(199, 244, 90));
        TextResultPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        StatusInfo.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        StatusInfo.setForeground(new java.awt.Color(0, 0, 0));
        StatusInfo.setText("Connection Status:");
        StatusInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        StatusInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        StatusInfo.setIconTextGap(7);

        Con1TextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Con1TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con2TextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Con2TextField.setForeground(new java.awt.Color(0, 0, 0));
        Con2TextField.setText("Awaiting client connection....");

        Con3TextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Con3TextField.setForeground(new java.awt.Color(0, 0, 0));

        Con4TextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Con4TextField.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout TextResultPanelLayout = new javax.swing.GroupLayout(TextResultPanel);
        TextResultPanel.setLayout(TextResultPanelLayout);
        TextResultPanelLayout.setHorizontalGroup(
            TextResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatusInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TextResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Con4TextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Con3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Con2TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Con1TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TextResultPanelLayout.setVerticalGroup(
            TextResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextResultPanelLayout.createSequentialGroup()
                .addComponent(StatusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Con2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Con4TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Con3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Con1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SearchBarButton.setBackground(new java.awt.Color(127, 57, 233));

        SearchBarTextField.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout SearchPanelBGLayout = new javax.swing.GroupLayout(SearchPanelBG);
        SearchPanelBG.setLayout(SearchPanelBGLayout);
        SearchPanelBGLayout.setHorizontalGroup(
            SearchPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelBGLayout.createSequentialGroup()
                .addComponent(SearchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchBarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        SearchPanelBGLayout.setVerticalGroup(
            SearchPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchBarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(SearchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        TopInfo2Panel.setBackground(new java.awt.Color(136, 113, 249));

        StopServerButton.setBackground(new java.awt.Color(255, 56, 79));
        StopServerButton.setForeground(new java.awt.Color(0, 0, 0));
        StopServerButton.setText("Stop Server");
        StopServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopServerButtonActionPerformed(evt);
            }
        });

        StartServerButton.setBackground(new java.awt.Color(199, 255, 189));
        StartServerButton.setForeground(new java.awt.Color(0, 0, 0));
        StartServerButton.setText("Start Server");
        StartServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartServerButtonActionPerformed(evt);
            }
        });

        Info1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Info1.setForeground(new java.awt.Color(0, 0, 0));
        Info1.setText("Don't know how to start a server?");

        Info2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Info2.setForeground(new java.awt.Color(0, 0, 0));
        Info2.setText("Just click this button!");

        Info3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Info3.setForeground(new java.awt.Color(0, 0, 0));
        Info3.setText("Want to stop the server connection?");

        Info4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Info4.setForeground(new java.awt.Color(0, 0, 0));
        Info4.setText("Just click this button!");

        javax.swing.GroupLayout TopInfo2PanelLayout = new javax.swing.GroupLayout(TopInfo2Panel);
        TopInfo2Panel.setLayout(TopInfo2PanelLayout);
        TopInfo2PanelLayout.setHorizontalGroup(
            TopInfo2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                .addGroup(TopInfo2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(Info1))
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(Info2))
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(StartServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(TopInfo2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Info3))
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Info4))
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(StopServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(210, 210, 210))
        );
        TopInfo2PanelLayout.setVerticalGroup(
            TopInfo2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                .addGroup(TopInfo2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Info1)
                        .addGap(1, 1, 1)
                        .addComponent(Info2)
                        .addGap(21, 21, 21)
                        .addComponent(StartServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Info3))
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Info4))
                    .addGroup(TopInfo2PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(StopServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopInfo2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(TopInfo2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
    this.setVisible(false);
    new NetworkUI().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void EConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EConnectionButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_EConnectionButtonActionPerformed

    private void StartServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartServerButtonActionPerformed
                isClicked = true;
                serverport = 12;
                createServer();
                //count++;
                
                SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                    @Override
                protected Void doInBackground() throws Exception {
                    startServer();

                    return null;
                    }
                };
                worker.execute();// TODO add your handling code here:
    }//GEN-LAST:event_StartServerButtonActionPerformed

    private void StopServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopServerButtonActionPerformed
                disconnectServer();        // TODO add your handling code here:
    }//GEN-LAST:event_StopServerButtonActionPerformed

    private void ManageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageButtonActionPerformed
    this.setVisible(false);
    new ManageNetwork(IP_Address,count,socket).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ManageButtonActionPerformed

    private void HistoryLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryLogsButtonActionPerformed
        this.setVisible(false);
        new HistoryLogs(IP_Address,count,socket).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryLogsButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);      // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstablishConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstablishConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstablishConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstablishConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EstablishConnection().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsButton;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Con1TextField;
    private javax.swing.JLabel Con2TextField;
    private javax.swing.JLabel Con3TextField;
    private javax.swing.JLabel Con4TextField;
    private javax.swing.JButton EConnectionButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HistoryLogsButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JLabel Info4;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JButton ManageButton;
    private javax.swing.JButton SearchBarButton;
    private javax.swing.JTextField SearchBarTextField;
    private javax.swing.JPanel SearchPanelBG;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton StartServerButton;
    private javax.swing.JLabel StatusInfo;
    private javax.swing.JButton StopServerButton;
    private javax.swing.JPanel TextResultPanel;
    private javax.swing.JPanel TopInfo2Panel;
    // End of variables declaration//GEN-END:variables
}
