/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IPT_Final;

/**
 *
 * @author User
 */
public class ManageNetwork extends javax.swing.JFrame {

    /**
     * Creates new form ManageNetwork
     */
    
    private String IP_Address;
    private int count;
    private String[] IP_Array;
    
    public ManageNetwork(String IPAddress, int counter) {
        initComponents();
        IP_Address = IPAddress;
        count = counter;
//        IPAdd1TextField.setText("");
//        IPAdd1TextField.setText(IP_Address);
        store(IP_Address);
        this.setResizable(false);
    }
    
    
        public void store(String IP_Address) {
        IP_Array[count] = IP_Address; // add the received data to the array at the current index
        count++; // increment the current index

        switch (count){
            case 1:
            IPAdd1TextField.setText("");
            IPAdd1TextField.setText(IP_Address);
            IPAdd1TextField.setEnabled(false);
            break;
            
            case 2:
            IPAdd2TextField.setText("");
            IPAdd2TextField.setText(IP_Address);    
            break;
            
            case 3:
            IPAdd3TextField.setText("");
            IPAdd3TextField.setText(IP_Address);    
            break;
            
            case 4:
            IPAdd4TextField.setText("");
            IPAdd4TextField.setText(IP_Address);    
            break;
            
            case 5:
            IPAdd5TextField.setText("");
            IPAdd5TextField.setText(IP_Address);    
            break;
            
            case 6:
            IPAdd6TextField.setText("");
            IPAdd6TextField.setText(IP_Address);    
            break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        EConnectionButton = new javax.swing.JButton();
        ManageButton = new javax.swing.JButton();
        HistoryLogsButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        AboutUsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        NetworkBox = new javax.swing.JPanel();
        ConPanel1 = new javax.swing.JPanel();
        ConUser1 = new javax.swing.JLabel();
        IPAdd1TextField = new javax.swing.JLabel();
        Con1Button = new javax.swing.JButton();
        ConPanel3 = new javax.swing.JPanel();
        ConUser3 = new javax.swing.JLabel();
        IPAdd3TextField = new javax.swing.JLabel();
        Con3Button = new javax.swing.JButton();
        ConPanel4 = new javax.swing.JPanel();
        ConUser4 = new javax.swing.JLabel();
        IPAdd4TextField = new javax.swing.JLabel();
        Con4Button = new javax.swing.JButton();
        ConPanel2 = new javax.swing.JPanel();
        ConUser2 = new javax.swing.JLabel();
        IPAdd2TextField = new javax.swing.JLabel();
        Con2Button = new javax.swing.JButton();
        ConPanel5 = new javax.swing.JPanel();
        ConUser5 = new javax.swing.JLabel();
        IPAdd5TextField = new javax.swing.JLabel();
        Con5Button = new javax.swing.JButton();
        ConPanel6 = new javax.swing.JPanel();
        ConUser6 = new javax.swing.JLabel();
        IPAdd6TextField = new javax.swing.JLabel();
        Con6Button = new javax.swing.JButton();
        Numbering = new javax.swing.JLabel();
        Connected1 = new javax.swing.JLabel();
        Connected2 = new javax.swing.JLabel();
        Connected3 = new javax.swing.JLabel();
        Connected4 = new javax.swing.JLabel();
        Connected5 = new javax.swing.JLabel();
        Connected6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(136, 113, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 676));

        Sidepanel.setBackground(new java.awt.Color(136, 113, 249));

        HomeButton.setBackground(new java.awt.Color(127, 57, 233));
        HomeButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeButton.setIconTextGap(60);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        EConnectionButton.setBackground(new java.awt.Color(127, 57, 233));
        EConnectionButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        EConnectionButton.setText("Establish Connection");
        EConnectionButton.setBorder(null);
        EConnectionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EConnectionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EConnectionButton.setIconTextGap(24);
        EConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EConnectionButtonActionPerformed(evt);
            }
        });

        ManageButton.setBackground(new java.awt.Color(127, 57, 233));
        ManageButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ManageButton.setText("Manage Networks");
        ManageButton.setBorder(null);
        ManageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ManageButton.setIconTextGap(14);

        HistoryLogsButton.setBackground(new java.awt.Color(127, 57, 233));
        HistoryLogsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HistoryLogsButton.setText("History Logs");
        HistoryLogsButton.setBorder(null);
        HistoryLogsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HistoryLogsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HistoryLogsButton.setIconTextGap(30);
        HistoryLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryLogsButtonActionPerformed(evt);
            }
        });

        SettingsButton.setBackground(new java.awt.Color(127, 57, 233));
        SettingsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        SettingsButton.setText("Settings");
        SettingsButton.setBorder(null);
        SettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SettingsButton.setIconTextGap(60);

        AboutUsButton.setBackground(new java.awt.Color(127, 57, 233));
        AboutUsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        AboutUsButton.setText("About Us");
        AboutUsButton.setBorder(null);
        AboutUsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AboutUsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AboutUsButton.setIconTextGap(54);

        ExitButton.setBackground(new java.awt.Color(127, 57, 233));
        ExitButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setBorder(null);
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ExitButton.setIconTextGap(73);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidepanelLayout = new javax.swing.GroupLayout(Sidepanel);
        Sidepanel.setLayout(SidepanelLayout);
        SidepanelLayout.setHorizontalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EConnectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
            .addComponent(ManageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistoryLogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AboutUsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidepanelLayout.setVerticalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EConnectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NetworkBox.setBackground(new java.awt.Color(127, 57, 233));
        NetworkBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        ConPanel1.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel1.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser1.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser1.setForeground(new java.awt.Color(0, 0, 0));
        ConUser1.setText("Connected User");

        IPAdd1TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd1TextField.setForeground(new java.awt.Color(0, 0, 0));
        IPAdd1TextField.setText("IP Address");

        Con1Button.setBackground(new java.awt.Color(127, 57, 233));

        javax.swing.GroupLayout ConPanel1Layout = new javax.swing.GroupLayout(ConPanel1);
        ConPanel1.setLayout(ConPanel1Layout);
        ConPanel1Layout.setHorizontalGroup(
            ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser1)
                .addGap(259, 259, 259)
                .addComponent(IPAdd1TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Con1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel1Layout.setVerticalGroup(
            ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd1TextField)
                            .addComponent(ConUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel3.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel3.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser3.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser3.setForeground(new java.awt.Color(0, 0, 0));
        ConUser3.setText("Connected User");

        IPAdd3TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd3TextField.setForeground(new java.awt.Color(0, 0, 0));
        IPAdd3TextField.setText("IP Address");

        Con3Button.setBackground(new java.awt.Color(127, 57, 233));

        javax.swing.GroupLayout ConPanel3Layout = new javax.swing.GroupLayout(ConPanel3);
        ConPanel3.setLayout(ConPanel3Layout);
        ConPanel3Layout.setHorizontalGroup(
            ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser3)
                .addGap(259, 259, 259)
                .addComponent(IPAdd3TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Con3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel3Layout.setVerticalGroup(
            ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd3TextField)
                            .addComponent(ConUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel4.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel4.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser4.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser4.setForeground(new java.awt.Color(0, 0, 0));
        ConUser4.setText("Connected User");

        IPAdd4TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd4TextField.setForeground(new java.awt.Color(0, 0, 0));
        IPAdd4TextField.setText("IP Address");

        Con4Button.setBackground(new java.awt.Color(127, 57, 233));

        javax.swing.GroupLayout ConPanel4Layout = new javax.swing.GroupLayout(ConPanel4);
        ConPanel4.setLayout(ConPanel4Layout);
        ConPanel4Layout.setHorizontalGroup(
            ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser4)
                .addGap(259, 259, 259)
                .addComponent(IPAdd4TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Con4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel4Layout.setVerticalGroup(
            ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd4TextField)
                            .addComponent(ConUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel2.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel2.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser2.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser2.setForeground(new java.awt.Color(0, 0, 0));
        ConUser2.setText("Connected User");

        IPAdd2TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd2TextField.setForeground(new java.awt.Color(0, 0, 0));
        IPAdd2TextField.setText("IP Address");

        Con2Button.setBackground(new java.awt.Color(127, 57, 233));

        javax.swing.GroupLayout ConPanel2Layout = new javax.swing.GroupLayout(ConPanel2);
        ConPanel2.setLayout(ConPanel2Layout);
        ConPanel2Layout.setHorizontalGroup(
            ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser2)
                .addGap(259, 259, 259)
                .addComponent(IPAdd2TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Con2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel2Layout.setVerticalGroup(
            ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd2TextField)
                            .addComponent(ConUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel5.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel5.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser5.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser5.setForeground(new java.awt.Color(0, 0, 0));
        ConUser5.setText("Connected User");

        IPAdd5TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd5TextField.setForeground(new java.awt.Color(0, 0, 0));
        IPAdd5TextField.setText("IP Address");

        Con5Button.setBackground(new java.awt.Color(127, 57, 233));

        javax.swing.GroupLayout ConPanel5Layout = new javax.swing.GroupLayout(ConPanel5);
        ConPanel5.setLayout(ConPanel5Layout);
        ConPanel5Layout.setHorizontalGroup(
            ConPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser5)
                .addGap(259, 259, 259)
                .addComponent(IPAdd5TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Con5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel5Layout.setVerticalGroup(
            ConPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd5TextField)
                            .addComponent(ConUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ConPanel6.setBackground(new java.awt.Color(199, 244, 90));
        ConPanel6.setPreferredSize(new java.awt.Dimension(0, 69));

        ConUser6.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ConUser6.setForeground(new java.awt.Color(0, 0, 0));
        ConUser6.setText("Connected User");

        IPAdd6TextField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IPAdd6TextField.setForeground(new java.awt.Color(0, 0, 0));
        IPAdd6TextField.setText("IP Address");

        Con6Button.setBackground(new java.awt.Color(127, 57, 233));

        javax.swing.GroupLayout ConPanel6Layout = new javax.swing.GroupLayout(ConPanel6);
        ConPanel6.setLayout(ConPanel6Layout);
        ConPanel6Layout.setHorizontalGroup(
            ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ConUser6)
                .addGap(259, 259, 259)
                .addComponent(IPAdd6TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Con6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ConPanel6Layout.setVerticalGroup(
            ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ConPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPAdd6TextField)
                            .addComponent(ConUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Con6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Numbering.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Numbering.setForeground(new java.awt.Color(0, 0, 0));
        Numbering.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Numbering.setText("No.");

        Connected1.setBackground(new java.awt.Color(0, 0, 0));
        Connected1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected1.setForeground(new java.awt.Color(0, 0, 0));
        Connected1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected1.setText("1");

        Connected2.setBackground(new java.awt.Color(0, 0, 0));
        Connected2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected2.setForeground(new java.awt.Color(0, 0, 0));
        Connected2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected2.setText("2");

        Connected3.setBackground(new java.awt.Color(0, 0, 0));
        Connected3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected3.setForeground(new java.awt.Color(0, 0, 0));
        Connected3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected3.setText("3");

        Connected4.setBackground(new java.awt.Color(0, 0, 0));
        Connected4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected4.setForeground(new java.awt.Color(0, 0, 0));
        Connected4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected4.setText("4");

        Connected5.setBackground(new java.awt.Color(0, 0, 0));
        Connected5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected5.setForeground(new java.awt.Color(0, 0, 0));
        Connected5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected5.setText("5");

        Connected6.setBackground(new java.awt.Color(0, 0, 0));
        Connected6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Connected6.setForeground(new java.awt.Color(0, 0, 0));
        Connected6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connected6.setText("6");

        javax.swing.GroupLayout NetworkBoxLayout = new javax.swing.GroupLayout(NetworkBox);
        NetworkBox.setLayout(NetworkBoxLayout);
        NetworkBoxLayout.setHorizontalGroup(
            NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(NetworkBoxLayout.createSequentialGroup()
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Numbering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(Connected1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ConPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ConPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ConPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ConPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        NetworkBoxLayout.setVerticalGroup(
            NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetworkBoxLayout.createSequentialGroup()
                .addComponent(Numbering, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Connected5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NetworkBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Connected6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NetworkBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NetworkBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistoryLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryLogsButtonActionPerformed
        this.setVisible(false);
        new HistoryLogs(IP_Address,count).setVisible(true);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryLogsButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
    this.setVisible(false);
    new NetworkUI().setVisible(true);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void EConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EConnectionButtonActionPerformed
    this.setVisible(false);
    new EstablishConnection().setVisible(true);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_EConnectionButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ManageNetwork(IP_Address,count).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsButton;
    private javax.swing.JButton Con1Button;
    private javax.swing.JButton Con2Button;
    private javax.swing.JButton Con3Button;
    private javax.swing.JButton Con4Button;
    private javax.swing.JButton Con5Button;
    private javax.swing.JButton Con6Button;
    private javax.swing.JPanel ConPanel1;
    private javax.swing.JPanel ConPanel2;
    private javax.swing.JPanel ConPanel3;
    private javax.swing.JPanel ConPanel4;
    private javax.swing.JPanel ConPanel5;
    private javax.swing.JPanel ConPanel6;
    private javax.swing.JLabel ConUser1;
    private javax.swing.JLabel ConUser2;
    private javax.swing.JLabel ConUser3;
    private javax.swing.JLabel ConUser4;
    private javax.swing.JLabel ConUser5;
    private javax.swing.JLabel ConUser6;
    private javax.swing.JLabel Connected1;
    private javax.swing.JLabel Connected2;
    private javax.swing.JLabel Connected3;
    private javax.swing.JLabel Connected4;
    private javax.swing.JLabel Connected5;
    private javax.swing.JLabel Connected6;
    private javax.swing.JButton EConnectionButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HistoryLogsButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel IPAdd1TextField;
    private javax.swing.JLabel IPAdd2TextField;
    private javax.swing.JLabel IPAdd3TextField;
    private javax.swing.JLabel IPAdd4TextField;
    private javax.swing.JLabel IPAdd5TextField;
    private javax.swing.JLabel IPAdd6TextField;
    private javax.swing.JButton ManageButton;
    private javax.swing.JPanel NetworkBox;
    private javax.swing.JLabel Numbering;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
