/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IPT_Final2;
import java.awt.Graphics;
import java.net.Socket;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

import javax.swing.SwingUtilities;
import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class HistoryLogs extends javax.swing.JFrame {
    private String[] ipArray;
    private int currentIndex = 0;
    /**
     * Creates new form HistoryLogs
     */
    public HistoryLogs() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(HistoryLogs.class.getResource("/Images/Server-Icon.png")));
        initComponents();
        ipArray = new String[5];
        this.setResizable(false);
    }

    public String Date(){
        LocalDate currentDate = LocalDate.now();
        LocalTime Time = LocalTime.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String formattedTime = Time.format(formatter);
        String formattedDate = currentDate.format(dateFormatter);
		return formattedDate + " " + formattedTime;}

    public void handleNewConnection(Socket socket) {
        if (socket != null) {
            String ipAddress = socket.getInetAddress().getHostAddress();
            String HostName = socket.getInetAddress().getHostName();
            int Port = socket.getPort();

            // Store the IP address in the array
            ipArray[currentIndex] = ipAddress;

            // Update the UI with the IP address of the new client
            switch (currentIndex) {
                case 0:
                	IpAddTextField1.setText(ipAddress);
                	Hostname1.setText(HostName);
                	Port1.setText("Port: "+Port);
                	DateTextField1.setText(Date());
                    break;
                case 1:
                	IpAddTextField2.setText(ipAddress);
                	Hostname2.setText(HostName);
                	Port2.setText("Port: "+Port);
                	DateTextField2.setText(Date());
                    break;
                case 2:
                	IpAddTextField3.setText(ipAddress);
                	Hostname3.setText(HostName);
                	Port3.setText("Port: "+Port);
                	DateTextField3.setText(Date());
                    break;
                case 3:
                	IpAddTextField4.setText(ipAddress);
                	Hostname4.setText(HostName);
                	Port4.setText("Port: "+Port);
                	DateTextField4.setText(Date());
                    break;
                case 4:
                	IpAddTextField5.setText(ipAddress);
                	Hostname5.setText(HostName);
                	Port5.setText("Port: "+Port);
                	DateTextField5.setText(Date());
                    break;
            }
            // Update the current index for the next IP address
            currentIndex = (currentIndex + 1) % ipArray.length;
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        ManageButton = new javax.swing.JButton();
        HistoryLogsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogsPanel = new javax.swing.JPanel();
        Log1 = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        IpAddTextField1 = new javax.swing.JLabel();
        IpAddTextField1.setText("IP Address");
        Text6 = new javax.swing.JLabel();
        DateTextField1 = new javax.swing.JLabel();
        Log2 = new javax.swing.JPanel();
        Text2 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        Log3 = new javax.swing.JPanel();
        Text3 = new javax.swing.JLabel();
        Log4 = new javax.swing.JPanel();
        Text4 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        Log5 = new javax.swing.JPanel();
        Text5 = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(136, 113, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(1194, 678));

        Sidepanel.setBackground(new java.awt.Color(136, 113, 249));

        ManageButton.setBackground(new java.awt.Color(127, 57, 233));
        ManageButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ManageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-manage-64.png"))); // NOI18N
        ManageButton.setText("Manage Networks");
        ManageButton.setBorder(null);
        ManageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ManageButton.setIconTextGap(14);
        ManageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageButtonActionPerformed(evt);
            }
        });

        HistoryLogsButton.setBackground(new java.awt.Color(127, 57, 233));
        HistoryLogsButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        HistoryLogsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-activity-history-64.png"))); // NOI18N
        HistoryLogsButton.setText("History Logs");
        HistoryLogsButton.setBorder(null);
        HistoryLogsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HistoryLogsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HistoryLogsButton.setIconTextGap(30);
        HistoryLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryLogsButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(127, 57, 233));
        ExitButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-close-48.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setBorder(null);
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ExitButton.setIconTextGap(73);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Duck6.png"))); // NOI18N

        javax.swing.GroupLayout SidepanelLayout = new javax.swing.GroupLayout(Sidepanel);
        Sidepanel.setLayout(SidepanelLayout);
        SidepanelLayout.setHorizontalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistoryLogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidepanelLayout.createSequentialGroup()
                .addGroup(SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SidepanelLayout.setVerticalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LogsPanel.setBackground(new java.awt.Color(127, 57, 233));

        Log1.setBackground(new java.awt.Color(127, 211, 235));

        Text1.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text1.setForeground(new java.awt.Color(0, 0, 0));
        Text1.setText("A user has connected:");

        IpAddTextField1.setFont(new Font("Century Gothic", Font.BOLD, 17)); // NOI18N
        IpAddTextField1.setForeground(new java.awt.Color(0, 0, 0));
        IpAddTextField1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        Text6.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text6.setForeground(new java.awt.Color(0, 0, 0));
        Text6.setText("at");

        DateTextField1.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        DateTextField1.setForeground(new java.awt.Color(0, 0, 0));
        DateTextField1.setText("(Date of connection)");
        
        Hostname1 = new JLabel();
        Hostname1.setText("(HostName)");
        Hostname1.setHorizontalAlignment(SwingConstants.LEFT);
        Hostname1.setForeground(Color.BLACK);
        Hostname1.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Port1 = new JLabel();
        Port1.setText("Port:");
        Port1.setHorizontalAlignment(SwingConstants.LEFT);
        Port1.setForeground(Color.BLACK);
        Port1.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        lblWith = new JLabel();
        lblWith.setText("with");
        lblWith.setHorizontalAlignment(SwingConstants.LEFT);
        lblWith.setForeground(Color.BLACK);
        lblWith.setFont(new Font("Century Gothic", Font.BOLD, 17));

        javax.swing.GroupLayout Log1Layout = new javax.swing.GroupLayout(Log1);
        Log1Layout.setHorizontalGroup(
        	Log1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Text1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(IpAddTextField1, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Hostname1, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblWith)
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addComponent(Port1, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Text6)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(DateTextField1, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        Log1Layout.setVerticalGroup(
        	Log1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(Log1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Log1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(Hostname1, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        					.addComponent(lblWith, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Log1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(DateTextField1, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        					.addComponent(Text6, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        					.addComponent(Port1, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
        				.addComponent(Text1, GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        				.addComponent(IpAddTextField1, GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        			.addContainerGap())
        );
        Log1.setLayout(Log1Layout);

//        if(count==1){
//            IpAddTextField1.setText("");
//            IpAddTextField1.setText(IP_Address);
//        }

        Log2.setBackground(new java.awt.Color(127, 211, 235));

        Text2.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text2.setForeground(new java.awt.Color(0, 0, 0));
        Text2.setText("A user has connected:");

        Text7.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text7.setForeground(new java.awt.Color(0, 0, 0));
        Text7.setText("at");
        
        DateTextField2 = new JLabel();
        DateTextField2.setText("(Date of connection)");
        DateTextField2.setForeground(Color.BLACK);
        DateTextField2.setFont(new Font("Century Gothic", Font.BOLD, 19));
        
        IpAddTextField2 = new JLabel();
        IpAddTextField2.setText("IP Address");
        IpAddTextField2.setHorizontalAlignment(SwingConstants.LEFT);
        IpAddTextField2.setForeground(Color.BLACK);
        IpAddTextField2.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Hostname2 = new JLabel();
        Hostname2.setText("(HostName)");
        Hostname2.setHorizontalAlignment(SwingConstants.LEFT);
        Hostname2.setForeground(Color.BLACK);
        Hostname2.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        lblWith_1 = new JLabel();
        lblWith_1.setText("with");
        lblWith_1.setHorizontalAlignment(SwingConstants.LEFT);
        lblWith_1.setForeground(Color.BLACK);
        lblWith_1.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Port2 = new JLabel();
        Port2.setText("Port:");
        Port2.setHorizontalAlignment(SwingConstants.LEFT);
        Port2.setForeground(Color.BLACK);
        Port2.setFont(new Font("Century Gothic", Font.BOLD, 17));

        javax.swing.GroupLayout Log2Layout = new javax.swing.GroupLayout(Log2);
        Log2Layout.setHorizontalGroup(
        	Log2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Text2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(IpAddTextField2, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Hostname2, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblWith_1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(Port2, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(Text7)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(DateTextField2, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        Log2Layout.setVerticalGroup(
        	Log2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(Log2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Port2, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblWith_1, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Hostname2, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(IpAddTextField2, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        				.addGroup(Log2Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(DateTextField2, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        					.addComponent(Text7, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        				.addComponent(Text2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        			.addContainerGap())
        );
        Log2.setLayout(Log2Layout);

        Log3.setBackground(new java.awt.Color(127, 211, 235));

        Text3.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text3.setForeground(new java.awt.Color(0, 0, 0));
        Text3.setText("A user has connected:");
        
        DateTextField3 = new JLabel();
        DateTextField3.setText("(Date of connection)");
        DateTextField3.setForeground(Color.BLACK);
        DateTextField3.setFont(new Font("Century Gothic", Font.BOLD, 19));
        
        Text7_1 = new JLabel();
        Text7_1.setText("at");
        Text7_1.setForeground(Color.BLACK);
        Text7_1.setFont(new Font("Century Gothic", Font.BOLD, 19));
        
        IpAddTextField3 = new JLabel();
        IpAddTextField3.setText("IP Address");
        IpAddTextField3.setHorizontalAlignment(SwingConstants.LEFT);
        IpAddTextField3.setForeground(Color.BLACK);
        IpAddTextField3.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Hostname3 = new JLabel();
        Hostname3.setText("(HostName)");
        Hostname3.setHorizontalAlignment(SwingConstants.LEFT);
        Hostname3.setForeground(Color.BLACK);
        Hostname3.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        lblWith_2 = new JLabel();
        lblWith_2.setText("with");
        lblWith_2.setHorizontalAlignment(SwingConstants.LEFT);
        lblWith_2.setForeground(Color.BLACK);
        lblWith_2.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Port3 = new JLabel();
        Port3.setText("Port:");
        Port3.setHorizontalAlignment(SwingConstants.LEFT);
        Port3.setForeground(Color.BLACK);
        Port3.setFont(new Font("Century Gothic", Font.BOLD, 17));

        javax.swing.GroupLayout Log3Layout = new javax.swing.GroupLayout(Log3);
        Log3Layout.setHorizontalGroup(
        	Log3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Text3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(IpAddTextField3, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Hostname3, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblWith_2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(Port3, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Text7_1, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(DateTextField3, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        Log3Layout.setVerticalGroup(
        	Log3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(Log3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Port3, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblWith_2, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Hostname3, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(IpAddTextField3, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Text7_1, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DateTextField3, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Text3, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        			.addContainerGap())
        );
        Log3.setLayout(Log3Layout);

        Log4.setBackground(new java.awt.Color(127, 211, 235));

        Text4.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text4.setForeground(new java.awt.Color(0, 0, 0));
        Text4.setText("A user has connected:");

        Text9.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text9.setForeground(new java.awt.Color(0, 0, 0));
        Text9.setText("at");
        
        DateTextField4 = new JLabel();
        DateTextField4.setText("(Date of connection)");
        DateTextField4.setForeground(Color.BLACK);
        DateTextField4.setFont(new Font("Century Gothic", Font.BOLD, 19));
        
        IpAddTextField4 = new JLabel();
        IpAddTextField4.setText("IP Address");
        IpAddTextField4.setHorizontalAlignment(SwingConstants.LEFT);
        IpAddTextField4.setForeground(Color.BLACK);
        IpAddTextField4.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Hostname4 = new JLabel();
        Hostname4.setText("(HostName)");
        Hostname4.setHorizontalAlignment(SwingConstants.LEFT);
        Hostname4.setForeground(Color.BLACK);
        Hostname4.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        lblWith_3 = new JLabel();
        lblWith_3.setText("with");
        lblWith_3.setHorizontalAlignment(SwingConstants.LEFT);
        lblWith_3.setForeground(Color.BLACK);
        lblWith_3.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Port4 = new JLabel();
        Port4.setText("Port:");
        Port4.setHorizontalAlignment(SwingConstants.LEFT);
        Port4.setForeground(Color.BLACK);
        Port4.setFont(new Font("Century Gothic", Font.BOLD, 17));

        javax.swing.GroupLayout Log4Layout = new javax.swing.GroupLayout(Log4);
        Log4Layout.setHorizontalGroup(
        	Log4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Text4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(IpAddTextField4, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Hostname4, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblWith_3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(Port4, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(Text9)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(DateTextField4, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        Log4Layout.setVerticalGroup(
        	Log4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, Log4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(Log4Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Port4, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblWith_3, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Hostname4, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(IpAddTextField4, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        				.addGroup(Log4Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(DateTextField4, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        					.addComponent(Text9, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        				.addComponent(Text4, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        			.addContainerGap())
        );
        Log4.setLayout(Log4Layout);

        Log5.setBackground(new java.awt.Color(127, 211, 235));

        Text5.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text5.setForeground(new java.awt.Color(0, 0, 0));
        Text5.setText("A user has connected:");

        Text10.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Text10.setForeground(new java.awt.Color(0, 0, 0));
        Text10.setText("at");
        
        DateTextField5 = new JLabel();
        DateTextField5.setText("(Date of connection)");
        DateTextField5.setForeground(Color.BLACK);
        DateTextField5.setFont(new Font("Century Gothic", Font.BOLD, 19));
        
        IpAddTextField5 = new JLabel();
        IpAddTextField5.setText("IP Address");
        IpAddTextField5.setHorizontalAlignment(SwingConstants.LEFT);
        IpAddTextField5.setForeground(Color.BLACK);
        IpAddTextField5.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Hostname5 = new JLabel();
        Hostname5.setText("(HostName)");
        Hostname5.setHorizontalAlignment(SwingConstants.LEFT);
        Hostname5.setForeground(Color.BLACK);
        Hostname5.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        lblWith_4 = new JLabel();
        lblWith_4.setText("with");
        lblWith_4.setHorizontalAlignment(SwingConstants.LEFT);
        lblWith_4.setForeground(Color.BLACK);
        lblWith_4.setFont(new Font("Century Gothic", Font.BOLD, 17));
        
        Port5 = new JLabel();
        Port5.setText("Port:");
        Port5.setHorizontalAlignment(SwingConstants.LEFT);
        Port5.setForeground(Color.BLACK);
        Port5.setFont(new Font("Century Gothic", Font.BOLD, 17));

        javax.swing.GroupLayout Log5Layout = new javax.swing.GroupLayout(Log5);
        Log5Layout.setHorizontalGroup(
        	Log5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log5Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Text5)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(IpAddTextField5, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Hostname5, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblWith_4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(Port5, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(Text10)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(DateTextField5, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        Log5Layout.setVerticalGroup(
        	Log5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Log5Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(Log5Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Port5, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblWith_4, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Hostname5, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        				.addComponent(IpAddTextField5, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        				.addGroup(Log5Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(DateTextField5, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        					.addComponent(Text10, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        				.addComponent(Text5, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        			.addContainerGap())
        );
        Log5.setLayout(Log5Layout);

        javax.swing.GroupLayout LogsPanelLayout = new javax.swing.GroupLayout(LogsPanel);
        LogsPanel.setLayout(LogsPanelLayout);
        LogsPanelLayout.setHorizontalGroup(
            LogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Log1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Log2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Log3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Log4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Log5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LogsPanelLayout.setVerticalGroup(
            LogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogsPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Log1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Log5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(136, 113, 249));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nezuko.gif"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(430, 0, 498, 276);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        jLabel5.setText("This panel informs you that a user has connected in your server");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 70, 490, 80);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        jLabel4.setText("It will show you the IP address of the client and the time");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 110, 440, 50);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        jLabel6.setText("that the client connected to the server.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 140, 300, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageButtonActionPerformed
//    this.setVisible(false);
    new ManageNetwork().setVisible(true);// TODO add your handling code here:
    
    }//GEN-LAST:event_ManageButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    this.setVisible(false);     // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void HistoryLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryLogsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryLogsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new HistoryLogs(IP_Address,socket).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateTextField1;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HistoryLogsButton;
    private javax.swing.JLabel IpAddTextField1;
    private javax.swing.JPanel Log1;
    private javax.swing.JPanel Log2;
    private javax.swing.JPanel Log3;
    private javax.swing.JPanel Log4;
    private javax.swing.JPanel Log5;
    private javax.swing.JPanel LogsPanel;
    private javax.swing.JButton ManageButton;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JLabel DateTextField2;
    private JLabel DateTextField4;
    private JLabel DateTextField5;
    private JLabel Hostname1;
    private JLabel Port1;
    private JLabel lblWith;
    private JLabel DateTextField3;
    private JLabel Text7_1;
    private JLabel IpAddTextField2;
    private JLabel IpAddTextField3;
    private JLabel IpAddTextField4;
    private JLabel IpAddTextField5;
    private JLabel Hostname2;
    private JLabel Hostname3;
    private JLabel Hostname4;
    private JLabel Hostname5;
    private JLabel lblWith_1;
    private JLabel lblWith_2;
    private JLabel lblWith_3;
    private JLabel lblWith_4;
    private JLabel Port2;
    private JLabel Port3;
    private JLabel Port4;
    private JLabel Port5;
    // End of variables declaration//GEN-END:variables
}
